insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (1,1.5,'Výborné zelené jablíčko','','Výborné zelené jablíčko, trochu kyselé, ale jinak mňamózní.',2,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (2,3.25,'Červená řepa','','Tahali červenou řepu, jako v pohádce.',6,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (3,15.25,'Brambory rané','','Výborné na hranolky!',7,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (4,9.3,'Brambory pozdní','','Staré, nahnilé, smrdí.',7,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (5,1.65,'Hruštičky jako ze stromu','','Sladké a šťavnaté, neber to!',3,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (6,3.7,'Mandarinky bez pecek','','Pár pecek se v nich občas najde.',4,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (7,3.6,'Mandarinky oranžové','','Klasické oranžové mandarinky s peckami.',4,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (8,10.29,'Mošt hruškový','','Nedochucovaný, neobarvovaný.',10,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (9,12.99,'Mošt multivitamin','','Namíchané zbytky všeho možného.',10,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (10,9.99,'Bezová šťáva','','Vymačkané bezinky s cukrem a vodou, klasika našich babiček.',11,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (11,10.99,'Rybízová šťáva','','Výtečný rybíz, čerstvě utržený.',11,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (12,21.99,'Víno Tramínek 2006','','Výtečný ročník 2006 + Vaše oblíbená odrůda, to chcete!',15,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (13,29.99,'Svatomartinské 2013','','Klasika klasik je zpět.',15,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (14,12.75,'Víno červené krabicové','','Klasický krabicák - hodně voltů za málo muziky.',14,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (15,999.95,'Víno červené krabicové extra','','Vylepšená verze staré klasiky. Nově se 40% alkoholu!',14,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (16,34.85,'Eidam 30','','Moc moc dobrá jídla. A já být dobrá kuchařka.',17,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (17,37.23,'Eidam 45','','Trochu silnější Eidámek.',17,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (18,45.36,'Gruyére','','Originál ze Švajcu.',17,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (19,41.90,'Gouda','','Naší Goudou vždy královsky pohostíte!',17,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (20,21.90,'Párečky svlíkačky','','Nejlepší poměr cena/výkon!',19,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (21,23.20,'Párky extra dlouhé','','Nabídněte si extra dlouhý hot-dog.',19,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (22,19.99,'Párky čertíci','','Jsou černý jak bota.',19,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (23,28.90,'Klobásky malé','','Malá verze klobásek.',20,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (24,29.90,'Klobásky střední','','Střední verze klobásek.',20,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (25,30.90,'Klobásky velké','','Velká verze klobásek.',20,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (26,34.90,'Šunka kuřecí prsní','','Výborná a relativně zdravá šunčička.',21,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (27,32.90,'Pražská šunka z Polska','','Trocha vody navíc, posypová sůl, bereš to?',21,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (28,1.59,'Rohlík 43g','','Klasika pečiv nesmí na Vašem stole chybět.',23,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (29,2.59,'Parádně vypečená houstička','','Ta křupe!',24,2);
insert into goods (id,cost,name,picture,text,category_id,vendor_id) values (30,9.90,'Chlebik z pece','','Chlebik rovnou z pece vytažený.',25,2);

INSERT INTO hibernate_sequences (sequence_name,sequence_next_hi_value) VALUES ('Goods',30);